version: 0.0
os: linux
files:
  - source: ./dist
    destination: /tmp/CodeDeployExample

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ubuntu
