version: 0.2
os: linux
files:
  - source: "dist"
    destination: /var/www/CypressPOC
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 3000
      runas: ec2-user

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 3000
      runas: ec2-user


