version: 0.2
env:
  variables:
    BUILD_Folder: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run test:ci
      - npm run build


