version: 0.2
env:
  variables:
    BUILD_Folder: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run test:ci
# post_build:
#    commands:
#      - aws s3 sync $BUILD_Folder s3://$S3_BUCKET_NAME

