version: 0.2
env:
  variables:
    BUILD_Folder: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      #curl https://intoli.com/install-google-chrome.sh | bash
      #- echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      #- apt-get -y update
      #- yum -y install google-chrome-stable
      
      - npm install
  pre_build:
    commands:
      - export CHROME_BIN=/usr/bin/google-chrome
      - npm install -g @angular/cli
      - npm i -D puppeteer
      #- sudo yum install -y libXcursor libXdamage libcups libXss libXrandr \ cups-libs dbus-glib libXinerama cairo cairo-gobject pango
      #- npm run test:ci
  build:
    commands:
      - npm run build
# post_build:
#    commands:
#      - aws s3 sync $BUILD_Folder s3://$S3_BUCKET_NAME

