version: 0.2
env:
  variables:
    BUILD_Folder: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      #- curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      #- echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      #- apt-get -y update
      #- apt-get -y install google-chrome-stable
      #- sudo apt-get install
      #- apt-get update
      -  wget http://security.ubuntu.com/ubuntu/pool/main/a/apt/apt_1.0.1ubuntu2.17_amd64.deb -O apt.deb
      - apt-get install -yq google-chrome-stable
      - npm install
  pre_build:
    commands:
      - export CHROME_BIN=/usr/bin/google-chrome
      - npm install -g @angular/cli
      - npm run test:ci
  build:
    commands:
      - npm run build
# post_build:
#    commands:
#      - aws s3 sync $BUILD_Folder s3://$S3_BUCKET_NAME

